# Demo of basic rotation matrix

In [16]:
# change Python Path
from pathlib import Path
pkg_dir = Path().resolve().parents[0]
import sys
sys.path.insert(0,str(pkg_dir.absolute()))

# import
from firefly.math.rotation_matrix import *
import numpy as np

# rotation angles
rotation_angle = np.rad2deg(45)




## Rotation along X

In [17]:
print(rotx(rotation_angle))

[[ 1.          0.          0.        ]
 [ 0.         -0.59181273  0.80607549]
 [ 0.         -0.80607549 -0.59181273]]


## Rotation along Y

In [18]:
print(roty(rotation_angle))

[[-0.59181273  0.         -0.80607549]
 [ 0.          1.          0.        ]
 [ 0.80607549  0.         -0.59181273]]


## Rotation along Z

In [19]:
print(rotz(rotation_angle))

[[-0.59181273  0.80607549  0.        ]
 [-0.80607549 -0.59181273  0.        ]
 [ 0.          0.          1.        ]]


## Error Handling

In [24]:
a = rotx(1)

BeartypeCallHintParamViolation: Function firefly.math.rotation_matrix.__fundamentalRotation() parameter theta=1 violates type hint <class 'float'>, as int 1 not instance of float.