In [5]:
# Import tools
import numpy as np

In [6]:
vector = np.array([1,2,3])
print(vector)
print(vector.shape)
print(np.ndim(vector))

[1 2 3]
(3,)
1


In [7]:
array_3x1 = vector.reshape(3, 1)
print(array_3x1)
print(array_3x1.shape)
print(np.ndim(array_3x1))

[[1]
 [2]
 [3]]
(3, 1)
2


In [11]:
matrix = np.array([[0, 1, 0],
                   [1, 0, 0],
                   [0, 0, 1]])
print(matrix)

print(matrix @ vector)
print(matrix @ array_3x1)


matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(matrix)

print(matrix @ vector)
print(matrix @ array_3x1)

[[0 1 0]
 [1 0 0]
 [0 0 1]]
[2 1 3]
[[2]
 [1]
 [3]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[14 32 50]
[[14]
 [32]
 [50]]
